[versions]
agp = "8.13.2"               # keep in sync with android-tools
android-tools = "31.13.2"    # = 23.0.0 + agp
compilerTesting = "0.12.1"
kotlin = "2.3.0"
kotlinPoet = "2.2.0"
ksp = "2.3.4"
ktlint = "1.7.1"
moshi = "1.15.2"

# Used by the sample app
compileSdk = "36"
minSdk = "24"


[libraries]
agp = { module = "com.android.tools.build:gradle", version.ref = "agp" }
javassist = { module = "org.javassist:javassist", version = "3.30.2-GA" }
compiler-testing-core = { module = "dev.zacsweers.kctfork:core", version.ref = "compilerTesting" }
compiler-testing-ksp = { module = "dev.zacsweers.kctfork:ksp", version.ref = "compilerTesting" }
featureDelivery = { module = "com.google.android.play:feature-delivery-ktx", version = "2.1.0"}
junit = { module = "junit:junit", version = "4.13.2" }
kotlin-stdlib-common = { module = "org.jetbrains.kotlin:kotlin-stdlib-common", version.ref = "kotlin" }
kotlin-gradle = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
kotlin-compiler = { module = "org.jetbrains.kotlin:kotlin-compiler-embeddable", version.ref = "kotlin" }
kotlinPoet-core = { module = "com.squareup:kotlinpoet", version.ref = "kotlinPoet" }
kotlinPoet-ksp = { module = "com.squareup:kotlinpoet-ksp", version.ref = "kotlinPoet" }
ksp-api = { module = "com.google.devtools.ksp:symbol-processing-api", version.ref = "ksp" }
ksp-gradlePlugin = { module = "com.google.devtools.ksp:symbol-processing-gradle-plugin", version.ref = "ksp" }
moshi-core = { module = "com.squareup.moshi:moshi", version.ref = "moshi" }
moshi-kotlin = { module = "com.squareup.moshi:moshi-kotlin", version.ref = "moshi" }
moshi-codegen = { module = "com.squareup.moshi:moshi-kotlin-codegen", version.ref = "moshi" }
truth = { module = "com.google.truth:truth", version = "1.4.5" }

# Used by the sample app
compose-bom = { module = "androidx.compose:compose-bom", version = "2026.01.01" }
compose-material = { module = "androidx.compose.material:material" }
compose-runtime = { module = "androidx.compose.runtime:runtime" }

compose-activity = { module = "androidx.activity:activity-compose", version = "1.10.1" }

# AGP things
google-guava = "com.google.guava:guava:33.5.0-jre"
google-gson = "com.google.code.gson:gson:2.13.2"
android-common = { module = "com.android.tools:common", version.ref = "android-tools" }
android-repository = { module = "com.android.tools:repository", version.ref = "android-tools" }
android-sdkCommon = { module = "com.android.tools:sdk-common", version.ref = "android-tools" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-dynamic-feature = { id = "com.android.dynamic-feature", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
publish = { id = "com.vanniktech.maven.publish", version = "0.36.0" }
spotless = { id = "com.diffplug.spotless", version = "8.0.0" }
wire = { id = "com.squareup.wire", version = "5.5.0" }

# Used by the sample app
# This is just a dummy version to make the verison catalog work. The real version is subsituted in the composite build.
betterDynamicFeatures = { id = "app.cash.better.dynamic.features", version = "0.0.0" }
